from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]
ASSETS_DIR = BASE_DIR / "assets"

WINDOW_TITLE = "SignEdge Unified Communicator"
APP_FPS = 30

LEFT_PANE_WIDTH = 1280
LEFT_PANE_HEIGHT = 720
RIGHT_PANE_WIDTH = 500

BOOT_GATE_SECONDS = 10.0

CAMERA_INDEX = 0
CAMERA_WIDTH = 960
CAMERA_HEIGHT = 540
CAMERA_FPS = 30

PIPER_VOICE = "en_US-amy-medium"
STT_MODEL_DIRNAME = "moonshine-small-streaming"
STT_MODEL_ARCH = 4
STT_SAMPLE_RATE = 16000
STT_BLOCK_SIZE = 4000
STT_UPDATE_INTERVAL = 0.35

ASL_SMOOTH_WINDOW = 7
ASL_CONFIDENCE_THRESHOLD = 0.65
ASL_HOLD_SECONDS = 0.85
ASL_RELEASE_SECONDS = 0.30
ASL_SEND_DWELL_SECONDS = 1.75
ASL_SEND_ZONE_RATIO = 0.22

EYE_EAR_THRESHOLD = 0.2
EYE_DWELL_TIME = 0.6
EYE_SMOOTHING_FRAMES = 20
EYE_CURSOR_ALPHA = 0.022
EYE_LLM_MODEL = "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
EYE_LLM_MODEL_PATH = BASE_DIR / EYE_LLM_MODEL
EYE_FREQUENCIES_FILE = ASSETS_DIR / "frequencies.txt"


MQTT_ENABLED = True
MQTT_BROKER_HOST = "192.168.137.197"
MQTT_BROKER_PORT = 1883
MQTT_BASE_TOPIC = "signedge/local"
MQTT_QOS = 0

DASHBOARD_HOST = "192.168.137.1"
DASHBOARD_PORT = 5050
